XCC_DIR=$(TOP)/..
XCC_INC_DIR=$(XCC_DIR)/inc
XCC_LIB_DIR=$(XCC_DIR)/lib

XCC_LIBS=\
	$(XCC_LIB_DIR)/lib.c \
	$(XCC_LIB_DIR)/sprintf.c \
	$(XCC_LIB_DIR)/umalloc.c \
	$(XCC_LIB_DIR)/math.c \
	$(XCC_LIB_DIR)/crt0.c

TCC=$(XCC_DIR)/xcc -I$(XCC_INC_DIR)

#include $(TOP)/config.mak
TOPSRC=$(TOP)
